const $=id=>document.getElementById(id);const f=(n,d=2)=>Number.isFinite(n)?n.toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d}):'—';const c=n=>Number.isFinite(n)?Math.abs(n)>=1e6?(n/1e6).toFixed(2)+'M':Math.abs(n)>=1e3?(n/1e3).toFixed(2)+'K':n.toFixed(2):'—';const pc=(n,d=2)=>Number.isFinite(n)?`${n>=0?'+':''}${n.toFixed(d)}%`:'—';
const S={spot:{bids:[],asks:[],bid:0,ask:0,bq:0,aq:0,ts:0,ready:false},fut:{bid:0,ask:0,last:0,ts:0,ready:false},prev:null,trades:[],depth:[],ofi:[],prices:[],adds:0,withdraw:0,bAdds:0,aAdds:0,retryS:0,retryF:0};
function txt(id,v){const e=$(id);if(e)e.textContent=v}function trim(a,x,n){a.push(x);if(a.length>n)a.splice(0,a.length-n)}function sum(a){return a.reduce((s,x)=>s+x[1],0)}function map(a){const m=new Map();a.forEach(x=>m.set(x[0],x[1]));return m}
function depth(d){const b=(d.bids||[]).map(x=>[+x[0],+x[1]]).filter(x=>x[1]>0).sort((a,z)=>z[0]-a[0]).slice(0,20),a=(d.asks||[]).map(x=>[+x[0],+x[1]]).filter(x=>x[1]>0).sort((x,z)=>x[0]-z[0]).slice(0,20);if(!b.length||!a.length)return;let o=0;if(S.prev){const p=S.prev;if(b[0][0]>p.b)o+=b[0][1];else if(b[0][0]===p.b)o+=b[0][1]-p.bq;else o-=p.bq;if(a[0][0]<p.a)o-=a[0][1];else if(a[0][0]===p.a)o-=a[0][1]-p.aq;else o+=p.aq;const ob=map(p.bids),oa=map(p.asks);for(const [q,n] of b){const old=ob.get(q)||0;if(n>old){S.adds+=n-old;S.bAdds+=n-old}else if(n<old)S.withdraw+=old-n}for(const [q,n] of a){const old=oa.get(q)||0;if(n>old){S.adds+=n-old;S.aAdds+=n-old}else if(n<old)S.withdraw+=old-n}}S.spot={...S.spot,bids:b,asks:a,bid:b[0][0],ask:a[0][0],bq:b[0][1],aq:a[0][1],ts:+(d.E||Date.now()),ready:true};S.prev={b:b[0][0],a:a[0][0],bq:b[0][1],aq:a[0][1],bids:b,asks:a};trim(S.ofi,{t:Date.now(),v:o},1000);trim(S.depth,Date.now(),1000)}
function ticker(d){const b=+d.b,a=+d.a;if(b&&a)S.spot={...S.spot,bid:b,ask:a,bq:+d.B,aq:+d.A,ts:+(d.E||Date.now()),ready:true}}function fticker(d){const b=+d.b,a=+d.a;if(b&&a)S.fut={bid:b,ask:a,last:(b+a)/2,ts:+(d.E||Date.now()),ready:true}}
function trade(d){const p=+d.p,q=+d.q;if(p&&q)trim(S.trades,{t:Date.now(),p,q,sign:d.m?-1:1},5000)}
function socket(url,fn,open,close){let w;try{w=new WebSocket(url)}catch(e){close();return}w.onopen=open;w.onclose=close;w.onerror=()=>{};w.onmessage=e=>{try{const x=JSON.parse(e.data),d=x.data||x;fn(d)}catch(_){}}}
function feeds(){const su='wss://stream.binance.com:9443/stream?streams=btcusdt@depth20@100ms/btcusdt@aggTrade/btcusdt@bookTicker',fu='wss://fstream.binance.com/stream?streams=btcusdt@bookTicker';const so=()=>{txt('spotState','LIVE');txt('wsStatus','LIVE DATA');$('wsDot').className='dot on';S.retryS=0},fo=()=>{txt('futuresState','LIVE');S.retryF=0},sc=()=>{txt('spotState','RETRY');setTimeout(ss,Math.min(10000,1000*2**S.retryS++))},fc=()=>{txt('futuresState','RETRY');setTimeout(fs,Math.min(10000,1000*2**S.retryF++))},ss=()=>socket(su,d=>{if(d.e==='depthUpdate')depth(d);else if(d.e==='bookTicker')ticker(d);else if(d.e==='aggTrade')trade(d)},so,sc),fs=()=>socket(fu,d=>{if(d.e==='bookTicker')fticker(d)},fo,fc);ss();fs()}
function tr5(){const n=Date.now();let b=0,s=0;for(const x of S.trades)if(n-x.t<5000)(x.sign>0?b+=x.q:s+=x.q);return{b,s,t:b+s}}function of5(){const n=Date.now();return S.ofi.reduce((z,x)=>n-x.t<5000?z+x.v:z,0)}function spark(id,v){const e=$(id);if(!e||v.length<2)return;const w=260,h=36,lo=Math.min(...v),hi=Math.max(...v),r=hi-lo||1,p=v.map((x,i)=>`${i*w/(v.length-1)},${h-2-(x-lo)/r*(h-5)}`).join(' ');e.innerHTML=`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><polyline fill="none" stroke="currentColor" stroke-width="1.5" points="${p}"/></svg>`}
function book(){const a=$('asks'),b=$('bids');a.innerHTML='';b.innerHTML='';const all=[...S.spot.bids,...S.spot.asks],mx=Math.max(...all.map(x=>x[1]),1);for(const [p,q] of S.spot.asks.slice(0,10).reverse()){const e=document.createElement('div');e.className='book-row ask';e.innerHTML=`<span>${p.toFixed(2)}</span><span>${q.toFixed(5)}</span><span>$${c(p*q)}</span>`;e.style.opacity=.45+.55*q/mx;a.appendChild(e)}for(const [p,q] of S.spot.bids.slice(0,10)){const e=document.createElement('div');e.className='book-row bid';e.innerHTML=`<span>${p.toFixed(2)}</span><span>${q.toFixed(5)}</span><span>$${c(p*q)}</span>`;e.style.opacity=.45+.55*q/mx;b.appendChild(e)}txt('bookMid',f((S.spot.bid+S.spot.ask)/2))}
function timeline(){const e=$('timeline');e.innerHTML='';const b=new Array(60).fill(0),n=Date.now();S.trades.forEach(x=>{const i=59-Math.floor((n-x.t)/1000);if(i>=0)b[i]+=x.sign*x.q});const mx=Math.max(...b.map(Math.abs),1);b.forEach(v=>{const d=document.createElement('div');d.className='barline';d.style.height=Math.max(2,Math.abs(v)/mx*100)+'%';e.appendChild(d)})}
function render(){const s=S.spot;if(!s.ready)return;const n=Date.now(),mid=(s.bid+s.ask)/2,sp=s.ask-s.bid,bd=sum(s.bids),ad=sum(s.asks),obi=(bd-ad)/(bd+ad||1),micro=(s.ask*s.bq+s.bid*s.aq)/(s.bq+s.aq||1),edge=(micro-mid)/mid*1e4,tr=tr5(),ag=tr.t?tr.b/tr.t:.5,ofi=of5(),dr=S.depth.filter(x=>n-x<5000).length/5,trr=S.trades.filter(x=>n-x.t<5000).length/5,add=S.adds,wd=S.withdraw;S.adds=S.withdraw=0;const score=Math.max(-1,Math.min(1,obi*.45+Math.tanh(ofi/(bd+ad+1)*20)*.25+(ag-.5)*.6+Math.tanh(edge/3)*.15));
 txt('price','$'+f(mid));txt('bid',f(s.bid));txt('ask',f(s.ask));txt('spread',f(sp));txt('obi',(obi*100).toFixed(1)+'%');txt('bidDepth',c(bd));txt('askDepth',c(ad));$('obiBid').style.width=(50+obi*50)+'%';$('obiAsk').style.width=(50-obi*50)+'%';txt('ofi',(ofi>=0?'+':'')+c(ofi));txt('buyPressure',c(tr.b));txt('sellPressure',c(tr.s));txt('aggression',(ag*100).toFixed(1)+'% BUY');txt('takerBuy',c(tr.b));txt('takerSell',c(tr.s));$('aggressionBar').style.width=ag*100+'%';txt('queue','N/A');txt('bidQueue',c(s.bq));txt('askQueue',c(s.aq));const cr=wd/(wd+add||1)*100;txt('cancelRate',cr.toFixed(1)+'%');txt('withdrawals',c(wd));txt('replenish',c(add));txt('arrival',f(dr+trr,1));txt('depthRate',f(dr,1));txt('tradeRate',f(trr,1));txt('replenishRate',f(add/.5,1));txt('bidAdds',c(S.bAdds));txt('askAdds',c(S.aAdds));$('replenishBar').style.width=Math.min(100,add*10)+'%';txt('spreadBps',(sp/mid*1e4).toFixed(2));txt('spreadAbs',f(sp));txt('mid',f(mid));txt('microprice',f(micro));txt('microEdge',(edge>=0?'+':'')+edge.toFixed(2)+' bps');txt('bias',score>.18?'BUY PRESSURE':score<-.18?'SELL PRESSURE':'BALANCED');txt('biasScore',score.toFixed(3));txt('confidence',(Math.abs(score)*100).toFixed(0)+'%');$('biasMeter').style.width=(50+score*50)+'%';$('bias').className='bias '+(score>.18?'positive':score<-.18?'negative':'neutral-text');
 txt('spotPrice',f(mid));txt('futuresPrice',f(s.fut.last));const basis=s.fut.ready?s.fut.last-mid:NaN;txt('basis',Number.isFinite(basis)?(basis>=0?'+':'')+basis.toFixed(2):'—');txt('basisBps',s.fut.ready?(basis/mid*1e4).toFixed(2)+' bps':'—');txt('venueTime',s.fut.ready?'Both Binance feeds live':'Waiting for futures feed…');txt('latency',Math.max(0,n-s.ts)+' ms');txt('lastUpdate',new Date().toLocaleTimeString());
 if(!S.prices.length||n-S.prices.at(-1).t>900)trim(S.prices,{t:n,p:mid},100);while(S.prices.length&&n-S.prices[0].t>60000)S.prices.shift();const r=[];for(let i=1;i<S.prices.length;i++)r.push(Math.log(S.prices[i].p/S.prices[i-1].p));const m=r.reduce((a,b)=>a+b,0)/(r.length||1),v=r.length>1?r.reduce((a,b)=>a+(b-m)**2,0)/(r.length-1):NaN;txt('vol',Number.isFinite(v)?(Math.sqrt(v)*Math.sqrt(31536000)*100).toFixed(1)+'%':'—');txt('ret1s',S.prices.length>1?pc((mid/S.prices.at(-2).p-1)*100,3):'—');const ps=S.prices.map(x=>x.p);txt('range1m',ps.length?((Math.max(...ps)-Math.min(...ps))/mid*100).toFixed(3)+'%':'—');spark('ofiSpark',S.ofi.slice(-80).map(x=>x.v));spark('priceSpark',S.prices.slice(-80).map(x=>x.p));spark('arrivalSpark',S.depth.slice(-60).map((_,i)=>i));book();timeline()}
setInterval(render,250);feeds();
