import React from 'react';
import { AbsoluteFill, Composition, Easing, Sequence, interpolate, spring, useCurrentFrame } from 'remotion';

const ease = Easing.bezier(0.16, 1, 0.3, 1);

const Glow: React.FC<{x:number;y:number;s:number;delay?:number}> = ({x,y,s,delay=0}) => {
  const f = useCurrentFrame();
  const pulse = 1 + Math.sin((f + delay) / 18) * 0.08;
  return <div style={{position:'absolute',left:x,top:y,width:s,height:s,borderRadius:'50%',background:'radial-gradient(circle, rgba(16,185,129,.22), rgba(59,130,246,.06) 45%, transparent 72%)',scale:pulse}} />;
};

const Text: React.FC<{children:React.ReactNode;size:number;weight?:number;delay?:number;muted?:boolean}> = ({children,size,weight=700,delay=0,muted=false}) => {
  const f=useCurrentFrame();
  return <div style={{opacity:interpolate(f,[delay,delay+10],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:ease}),translate:interpolate(f,[delay,delay+16],['0px 45px','0px 0px'],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:ease}),fontSize:size,fontWeight:weight,letterSpacing:size>70?'-4px':'-1px',lineHeight:1.02,color:muted?'rgba(226,232,240,.68)':'#f8fafc',textAlign:'center',fontFamily:'Inter, ui-sans-serif, system-ui, sans-serif'}}>{children}</div>;
};

const ChatLogo = ({size=210}:{size?:number}) => {
  const f=useCurrentFrame();
  return <div style={{width:size,height:size,borderRadius:size*.28,background:'linear-gradient(145deg,#10b981,#14b8a6)',display:'flex',alignItems:'center',justifyContent:'center',boxShadow:'0 0 80px rgba(16,185,129,.28)',rotate:interpolate(f,[0,30],[-7,0],{extrapolateRight:'clamp',easing:ease}),scale:spring({frame:f,fps:30,config:{damping:16,mass:.7,stiffness:90}})}}>
    <div style={{width:size*.53,height:size*.53,border:'8px solid white',borderRadius:'48%',position:'relative',boxSizing:'border-box'}}>
      <div style={{position:'absolute',width:size*.10,height:size*.10,borderRadius:'50%',background:'white',left:size*.11,top:size*.18}}/><div style={{position:'absolute',width:size*.10,height:size*.10,borderRadius:'50%',background:'white',right:size*.11,top:size*.18}}/>
      <div style={{position:'absolute',width:size*.27,height:size*.12,borderBottom:'7px solid white',borderRadius:'0 0 100px 100px',left:size*.12,top:size*.27}}/>
    </div>
  </div>;
};

const Scene1=()=>{const f=useCurrentFrame();return <AbsoluteFill style={{background:'#050816',alignItems:'center',justifyContent:'center',overflow:'hidden'}}><Glow x={-120} y={-80} s={600}/><Glow x={900} y={1100} s={700}/><div style={{opacity:interpolate(f,[0,12],[0,1],{extrapolateRight:'clamp',easing:ease}),scale:interpolate(f,[0,18],[.55,1],{extrapolateRight:'clamp',easing:Easing.out(Easing.exp)})}}><ChatLogo/></div><div style={{position:'absolute',top:1080}}><Text size={92}>Meet ChatGPT.</Text></div><div style={{position:'absolute',top:1205}}><Text size={36} weight={500} muted delay={8}>A new way to interact with AI.</Text></div></AbsoluteFill>};

const Scene2=()=>{const f=useCurrentFrame(); const p=interpolate(f,[0,24],[0,1],{extrapolateRight:'clamp',easing:ease}); return <AbsoluteFill style={{background:'#070a13',overflow:'hidden',padding:110,boxSizing:'border-box'}}><Glow x={700} y={-100} s={800}/><div style={{position:'absolute',top:180,left:110}}><Text size={76}>So… what is it?</Text></div><div style={{position:'absolute',top:430,left:110,right:110,height:430,borderRadius:38,border:'1px solid rgba(148,163,184,.18)',background:'rgba(15,23,42,.78)',boxShadow:'0 30px 100px rgba(0,0,0,.35)',padding:55,boxSizing:'border-box',translate:interpolate(f,[0,20],['0px 80px','0px 0px'],{extrapolateRight:'clamp',easing:ease}),opacity:p}}><div style={{fontSize:31,color:'#94a3b8',marginBottom:25,fontFamily:'Inter, sans-serif'}}>YOU</div><div style={{fontSize:46,color:'#f8fafc',fontWeight:600,fontFamily:'Inter, sans-serif'}}>Explain artificial intelligence<br/>like I’m five.</div><div style={{position:'absolute',right:45,bottom:35,fontSize:25,color:'#10b981',fontFamily:'Inter, sans-serif'}}>Send ↗</div></div><div style={{position:'absolute',top:930,left:110,right:110}}><div style={{height:5,width:`${p*100}%`,background:'linear-gradient(90deg,#10b981,#3b82f6)',borderRadius:10}}/></div></AbsoluteFill>};

const Scene3=()=>{const f=useCurrentFrame(); const bars=[.25,.45,.33,.72,.52,.86,.61,.94,.7,.48,.8,.58]; return <AbsoluteFill style={{background:'#030712',overflow:'hidden',alignItems:'center',justifyContent:'center'}}><Glow x={-250} y={400} s={900}/><Glow x={1000} y={100} s={800}/><div style={{position:'absolute',top:130}}><Text size={72}>It reads. It reasons. It responds.</Text></div><div style={{position:'absolute',top:460,width:1180,height:500,borderRadius:44,background:'linear-gradient(135deg,rgba(15,23,42,.92),rgba(17,24,39,.62))',border:'1px solid rgba(148,163,184,.15)',display:'flex',alignItems:'center',justifyContent:'center',gap:34,padding:50,boxSizing:'border-box'}}>{bars.map((h,i)=><div key={i} style={{width:54,height:300,borderRadius:30,background:'linear-gradient(180deg,#34d399,#2563eb)',scale:`1 ${interpolate(f,[i*4,i*4+18],[.12,h],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)})}`,transformOrigin:'bottom'}}/> )}</div><div style={{position:'absolute',top:1010}}><Text size={32} weight={500} muted delay={12}>Behind the interface: patterns, context, and probabilities.</Text></div></AbsoluteFill>};

const Scene4=()=>{const f=useCurrentFrame(); const cards=[['WRITE','Draft emails, scripts, ideas'],['LEARN','Break down complex topics'],['CREATE','Brainstorm and explore'],['CODE','Build, debug, explain']]; return <AbsoluteFill style={{background:'#050816',padding:100,boxSizing:'border-box',overflow:'hidden'}}><Glow x={500} y={-220} s={1000}/><div style={{position:'absolute',top:110,left:100}}><Text size={70}>One assistant.</Text></div><div style={{position:'absolute',top:210,left:100}}><Text size={70}>Countless possibilities.</Text></div><div style={{position:'absolute',top:470,left:100,right:100,display:'grid',gridTemplateColumns:'1fr 1fr',gap:24}}>{cards.map(([a,b],i)=><div key={a} style={{height:220,borderRadius:32,padding:34,boxSizing:'border-box',background:'rgba(15,23,42,.75)',border:'1px solid rgba(148,163,184,.14)',opacity:interpolate(f,[15+i*6,27+i*6],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:ease}),translate:interpolate(f,[15+i*6,30+i*6],['0px 50px','0px 0px'],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:ease})}}><div style={{fontSize:25,fontWeight:800,color:'#34d399',fontFamily:'Inter'}}>{a}</div><div style={{fontSize:31,fontWeight:600,color:'#e2e8f0',marginTop:20,fontFamily:'Inter'}}>{b}</div></div>)}</div></AbsoluteFill>};

const Scene5=()=>{const f=useCurrentFrame();return <AbsoluteFill style={{background:'#020617',overflow:'hidden',alignItems:'center',justifyContent:'center'}}><Glow x={-300} y={-300} s={1000}/><Glow x={1000} y={700} s={1000}/><div style={{opacity:interpolate(f,[0,15],[0,1],{extrapolateRight:'clamp',easing:ease}),scale:interpolate(f,[0,20],[.75,1],{extrapolateRight:'clamp',easing:ease})}}><ChatLogo size={170}/></div><div style={{position:'absolute',top:570}}><Text size={94} delay={8}>The future of conversation</Text></div><div style={{position:'absolute',top:700}}><Text size={94} delay={12}>is already here.</Text></div><div style={{position:'absolute',top:910}}><Text size={30} weight={500} muted delay={18}>ChatGPT · AI that works with you</Text></div></AbsoluteFill>};

export const ChatGPTIntro=()=> <AbsoluteFill style={{background:'#050816'}}><Sequence from={0} durationInFrames={135}><Scene1/></Sequence><Sequence from={135} durationInFrames={150}><Scene2/></Sequence><Sequence from={285} durationInFrames={165}><Scene3/></Sequence><Sequence from={450} durationInFrames={165}><Scene4/></Sequence><Sequence from={615} durationInFrames={135}><Scene5/></Sequence></AbsoluteFill>;

export const RemotionRoot=()=> <><Composition id="ChatGPTIntro" component={ChatGPTIntro} durationInFrames={750} fps={30} width={1080} height={1920}/></>;
